config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "game/start"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "game#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
	# Display the index page
  def index
  end

  # Start the Tic Tac Toe game
  def start
    # Retrieve first and second player names from params
    @first_player ||= tik_tak_toe_params[:first_player]
    @second_player ||= tik_tak_toe_params[:second_player]
    
    # Initialize the game board
    @board = Array.new(9)

    # If both player names are present, render the game board
    if @first_player.present? && @second_player.present?
      render 'board'
    else
      # If player names are missing, display a warning message and redirect to the root path
      flash[:warning] = "Please input your players name"
      redirect_to root_path
    end
  end

  private

  # Permit first_player and second_player parameters
  def tik_tak_toe_params
    params.permit(:first_player, :second_player)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/_player_names_form.html.erb
<%= form_with url: game_start_path, method: :post, id: 'player-names-form', data: { turbo: false } do |f| %>
  <div class="form-group text-white">
    <%= f.label :first_player, "Player 1 Name:" %>
    <%= f.text_field :first_player, class: 'form-control' %>
  </div>
  <div class="form-group text-white">
    <%= f.label :second_player, "Player 2 Name:" %>
    <%= f.text_field :second_player, class: 'form-control' %>
  </div>
  <%= f.submit "Start Game", class: 'btn btn-primary' %>
<% end %>

app/views/game/board.html.erb
<div id="tic-tac-toe-main" data-controller="tic-tac-toe" data-first-player-name="<%= @first_player %>" data-second-player-name="<%= @second_player %>">
  <main class="background">
    <section class="title">
      <h1>Tic Tac Toe</h1>
    </section>
    <section class="display" data-tic-tac-toe-target="playerDisplay">
      Player <span class="display-player playerX">X</span>'s turn
    </section>
    <section class="container" data-tic-tac-toe-target="ticTacToeBoard"></section>
    <section class="display announcer hide" data-tic-tac-toe-target="announcer"></section>
    <section id="notification-container"></section>
    <section class="controls">
      <button id="end-turn" class="btn btn-primary" data-tic-tac-toe-target="endTurnButton" data-action="click->tic-tac-toe#endTurn">End turn</button>
      <button id="reset" class="btn btn-secondary" data-action="click->tic-tac-toe#handleReset">Reset</button>
    </section>
  </main>
</div>

app/views/game/index.html.erb
<main class="background">
  <%= render 'shared/toast' %>
  <div class="container mt-5">
    <% if @player1_name && @player2_name %>
	    redirect_to game_board_path
    <% else %>
      <%= render 'player_names_form' %>
    <% end %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <!-- Set viewport to adjust layout on different devices -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <!-- Cross-Site Request Forgery (CSRF) meta tags -->
    <%= csrf_meta_tags %>
    
    <!-- Content Security Policy (CSP) meta tag for security -->
    <%= csp_meta_tag %>

    <!-- Link to the main application stylesheet -->
    <%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>
    
    <!-- Set Turbo visit control to reload -->
    <meta name="turbo-visit-control" content="reload">
    
    <!-- Import JavaScript modules via import map -->
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Render content dynamically -->
    <%= yield %>
    
    <!--
      Define environment variables for the client-side
      related to this bug: https://github.com/rails/importmap-rails/issues/65
    -->
    <script>
      window.process = { env: { NODE_ENV: 'production'} }
    </script>
  </body>
</html>

app/views/shared/_toast.html.erb
<div data-controller="flash-toast">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>